name: chartreuse_d
description: An Famix Meta model Importer for Dart.
version: 0.0.1
# homepage: https://www.example.com

environment:
  sdk: '>=2.15.0 <3.0.0'


# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
dependencies: 
  analyzer: ^4.1.0
  synchronized: ^3.0.0
